CREATE TABLE incidents (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(36) NOT NULL,
    incident_code VARCHAR(50) NOT NULL,
    incident_type VARCHAR(50) NOT NULL,
    severity VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    reported_at DATETIME(6) NOT NULL,
    reported_by_user_id BIGINT NULL,
    reported_by_name_snapshot VARCHAR(150) NOT NULL,
    related_ride_id BIGINT NULL,
    related_driver_id BIGINT NULL,
    related_vehicle_id BIGINT NULL,
    related_rider_id BIGINT NULL,
    related_guardian_id BIGINT NULL,
    related_organization_id BIGINT NULL,
    assigned_to_user_id BIGINT NULL,
    resolution_summary VARCHAR(2000) NULL,
    root_cause_summary VARCHAR(2000) NULL,
    corrective_action_summary VARCHAR(2000) NULL,
    notes VARCHAR(4000) NULL,
    status VARCHAR(30) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT pk_incidents PRIMARY KEY (id),
    CONSTRAINT uq_incidents_tenant_code UNIQUE (tenant_id, incident_code),
    CONSTRAINT fk_incidents_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_incidents_reported_user FOREIGN KEY (reported_by_user_id) REFERENCES app_users(id),
    CONSTRAINT fk_incidents_assigned_user FOREIGN KEY (assigned_to_user_id) REFERENCES app_users(id)
);

CREATE INDEX idx_incidents_tenant_status ON incidents (tenant_id, status);
CREATE INDEX idx_incidents_tenant_severity ON incidents (tenant_id, severity);
CREATE INDEX idx_incidents_tenant_reported_at ON incidents (tenant_id, reported_at);

CREATE TABLE tenant_settings (
    tenant_id VARCHAR(36) NOT NULL,
    timezone VARCHAR(80) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    date_format VARCHAR(30) NOT NULL,
    default_ride_lead_time_minutes INT NOT NULL,
    allow_manual_ride_creation BIT NOT NULL,
    allow_round_trip_rides BIT NOT NULL,
    dispatch_strict_compliance_mode BIT NOT NULL,
    default_invoice_due_days INT NOT NULL,
    default_notification_preferences_summary VARCHAR(500) NULL,
    require_driver_license BIT NOT NULL,
    require_background_check BIT NOT NULL,
    require_drug_test BIT NOT NULL,
    require_vehicle_registration BIT NOT NULL,
    require_vehicle_insurance BIT NOT NULL,
    require_vehicle_inspection BIT NOT NULL,
    expiring_soon_threshold_days INT NOT NULL,
    invoice_prefix VARCHAR(20) NOT NULL,
    payment_prefix VARCHAR(20) NOT NULL,
    pricing_rule_prefix VARCHAR(20) NOT NULL,
    tax_enabled BIT NOT NULL,
    default_tax_rate DECIMAL(5,2) NOT NULL,
    allow_manual_invoice_overrides BIT NOT NULL,
    company_logo_url VARCHAR(500) NULL,
    primary_color VARCHAR(20) NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT pk_tenant_settings PRIMARY KEY (tenant_id),
    CONSTRAINT fk_tenant_settings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);