package com.transportplatform.tms.features.notification.domain;

public enum NotificationType {
    COMPANY_APPLICATION_SUBMITTED,
    COMPANY_APPLICATION_APPROVED,
    COMPANY_APPLICATION_REJECTED,
    COMPANY_USER_CREATED,
    USER_INVITATION,
    COMPANY_USER_ACTIVATED,
    COMPANY_USER_SUSPENDED,
    DRIVER_STATUS_CHANGED,
    DRIVER_DOCUMENT_VERIFIED,
    DRIVER_DOCUMENT_EXPIRING,
    DRIVER_DOCUMENT_EXPIRED,
    DRIVER_DOCUMENT_REJECTED,
    VEHICLE_DOCUMENT_VERIFIED,
    VEHICLE_DOCUMENT_EXPIRING,
    VEHICLE_DOCUMENT_EXPIRED,
    VEHICLE_DOCUMENT_REJECTED,
    RIDE_DRIVER_ASSIGNED,
    RIDE_VEHICLE_ASSIGNED,
    RIDE_STATUS_CHANGED,
    INVOICE_ISSUED,
    PAYMENT_RECORDED,
    PAYMENT_APPLIED,
    RECEIVABLE_OVERDUE_REMINDER,
    COMPLIANCE_ISSUE_OPENED
}