server:
  forward-headers-strategy: framework

spring:
  flyway:
    enabled: true
    locations: classpath:db/prod-bootstrap
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  bootstrap:
    platform-admin:
      enabled: ${APP_BOOTSTRAP_PLATFORM_ADMIN_ENABLED:true}
      email: ${APP_BOOTSTRAP_PLATFORM_ADMIN_EMAIL:samuelweld2019@gmail.com}
      password: ${APP_BOOTSTRAP_PLATFORM_ADMIN_PASSWORD:Password123}
  security:
    api-docs-enabled: false

logging:
  level:
    root: ${APP_LOGGING_LEVEL_ROOT:INFO}
    "[com.transportplatform.tms]": ${APP_LOGGING_LEVEL_APP:INFO}
    "[org.springframework.web]": ${APP_LOGGING_LEVEL_WEB:WARN}
    "[org.springframework.security]": ${APP_LOGGING_LEVEL_SECURITY:INFO}
    "[org.hibernate.SQL]": ${APP_LOGGING_LEVEL_SQL:INFO}
    "[org.hibernate.orm.jdbc.bind]": ${APP_LOGGING_LEVEL_SQL_BIND:INFO}
