server:
  forward-headers-strategy: framework

spring:
  jpa:
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  bootstrap:
    platform-admin:
      enabled: ${APP_BOOTSTRAP_PLATFORM_ADMIN_ENABLED:false}
  security:
    api-docs-enabled: false

logging:
  level:
    root: ${APP_LOGGING_LEVEL_ROOT:INFO}
    "[com.transportplatform.tms]": ${APP_LOGGING_LEVEL_APP:DEBUG}
    "[org.springframework.web]": ${APP_LOGGING_LEVEL_WEB:DEBUG}
    "[org.springframework.security]": ${APP_LOGGING_LEVEL_SECURITY:INFO}
    "[org.hibernate.SQL]": ${APP_LOGGING_LEVEL_SQL:INFO}
    "[org.hibernate.orm.jdbc.bind]": ${APP_LOGGING_LEVEL_SQL_BIND:INFO}
